### ISSUE TITLE
[Feature Request] Add fallback if no changes are staged

### ISSUE THREAD

**Issue by SivertGullbergHansen** [JepriCreations/commitollama#3]
✨ Right now there seems to be no checks if no staged content is found. 

I receive this as a default fallback:
```md
refactor ♻️: Simplified login form processing

Explanation: Based on the provided context, it seems that the changes made were focused on 
refactoring the login form processing. The commit message should reflect
```

Should instead disable the button or return a warning saying "Stage your changes first!", alternatively if no changes are staged then run `git add .` and run commitollama

**Comment by JepriCreations** [comment]
Fixed in v1.5.1
