### ISSUE TITLE
Print text of exception from ollama. 

### ISSUE THREAD

**Issue by belonesox** [JepriCreations/commitollama#5]
Please, lets print text of exception from ollama.

Now on any ollama exception we get false "Unable to connect" message.

![image](https://github.com/JepriCreations/commitollama/assets/1609739/1ed0790d-1c1e-44be-a6f2-182dd7353d21)

**Comment by YesnielX** [comment]
Have you downloaded the mistral model? It says it has not been found. run `ollama pull mistral`

**Comment by belonesox** [comment]
Yes, I download model. Later. But first I spent lot of time thinking that I have connectivity problem with ollama server. So "lets print text of exception from ollama"
